# Generated by Django 3.0.4 on 2020-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=255)),
                ('user_department', models.CharField(max_length=50)),
                ('user_telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
