# Generated by Django 3.0.4 on 2020-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AchieveItDependencies', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessField',
            fields=[
                ('business_field_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('business_field_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectId',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
